services:
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: annie
      MONGO_INITDB_ROOT_PASSWORD: inkcherry
    volumes:
      - ./mongo:/app
      - ./mongo_data:/data/db
    working_dir: /app
  app:
    image: node:latest
    command: npm run start
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./next:/app
    working_dir: /app
    depends_on:
      - db
